export const texts = {
  resendCount: 'Resend in 00:',
  resendCode: 'Resend',
  appName: 'DigiNerve',
  permissionRequired: 'Permission Required!',
  ok: 'Ok',
  noAvaiable: 'Not Available',
  cancel: 'Cancel',
  premiumAccessText: 'Access\n Premium Content',
  subHeadingPremiumAccess: 'Anytime, Anywhere',
  loginOrRegister: 'Log In or Register',
  phoneNumber: 'Enter phone number',
  learnHeading: 'Learn from the best in the industry anytime, anywhere.',
  loginWithEmail: 'Log In with Email',
  loginWithPhone: 'Log In with Phone',
  password: 'Password',
  accountCreate: 'Create Your Account',
  startLearning: 'Begin your learning journey with DigiNerve.',
  fullName: 'Full Name',
  email: 'Email',
  register: 'Register',
  iAgree: 'I agree to ',
  termsAndConditions: 'Terms and Conditions',
  and: ' and ',
  privacyPolicy: 'Privacy Policy.',
  verifyOtp: 'Verify OTP',
  verifyDescription: 'Please enter the 4-digit OTP sent to your ',
  phone_: 'phone number.',
  email_: 'email.',
  notReceivedOtp: 'Didn’t receive the OTP?',
  sendWhatsapp: 'Send on Whatsapp',
  login: 'Log In',
  forgotPassword: 'Forgot Password',
  verifyOtpSend: 'Verification OTP resent.',
  personalize: "Let's Personalise Your Experience",
  hi: 'Hi, ',
  underGrad: 'UnderGrad | Intern',
  postGrad: 'PostGrad | Professional',
  specialGrad: 'Super Specialisation',
  searchInsitute: 'Search Institute',
  searchSpecialization: 'Search Specialisation',
  enterSpecialization: 'Enter specialization',
  forgotPasswordQuestion: 'Forgot Password?',
  forgotPasswordDescription:
    'Enter your registered email to reset your password.',
  continue: 'Continue',
  backToLogin: 'Back to Login',
  linkSent: 'Link Sent!',
  linkSentDescriptionOne: 'We have sent an email to ',
  linkSentDescriptionTwo: ' with a link to reset your password.',
  done: 'Done',
  add: 'Add',
  enterDetails: 'Enter Details',
  city: 'City',
  state: 'State',
  save: 'Save',
  courses: ' courses',
  subscribedTo: 'You’re subscribed to',
  changePassword: 'Change Password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmPasssord: 'Confirm Password',
  minThreeCharacters: 'Minimum 3 characters',
  resetPassword: 'Reset Password',
  answerNow: 'Answer Now',
  questionOfTheDay: 'Question of the Day',
  continueLearning: 'Continue Learning',
  recommendedVideos: 'Recommended Videos',
  gotDoubts: 'Got Doubts?',
  askThe: 'Ask the',
  expert: 'Expert',
  join: 'Join',
  forums: 'Forums',
  signOut: 'Sign Out',
  upcomingEvents: 'Upcoming Events',
  registerNow: 'Register Now',
  knowMore: 'Know More',
  shareWithFriendsGetAmazonVoucher:
    'Share with your friends & get your Amazon Voucher!',
  shareApp: 'Share App Now',
  upcoming_Events: 'Upcoming Events',
  next: 'Next',
  back: 'Back',
  cannot_find: 'Can’t find? ',
  addManually: 'Add Institute Manually',
  enterManual: 'Enter Manually!',
  addManuallyDesc: 'Enter the name along with the city and state.',
  enter_institute_name: 'Enter Institute Name',
  submit: 'Submit',
  noResultFound: 'No results found!',
  joinNow: 'Join Now',
  dashboard: 'Dashboard',
  skip: 'Skip',
  interMode: 'Intern Mode',
  buy_Product: 'Buy Products',
  //Static
  dummyTitle: 'Ophthalmology MD',

  dummyName: 'Hello, Praveen Kumar',
  dummyVideoContinueLearning: 'Ophthalmology Md',
  dummyTimeLeft: '77 min left',
  dummyVoucherWorth: 'Voucher worth ₹1,000',
  dummyUserName: 'Praveen Kumar',
  dummyUserSpecialisation: 'Undergrad',
  dummyQuestion:
    'An 11-year-old boy presents with recurrent seizures for the past 10 days. Physical examination reveals hyper-pigmented papules on the face,',
  dummyQuestionOne:
    ' hypo-pigmented macules on the lower limbs, and a Shagreen patch on the right buttock',
  dummyQuestionTwo:
    "Neurological examination shows increased tone in all limbs, brisk deep tendon reflexes, and bilateral positive Babinski's sign, but absent superficial reflexes.",
  dummyQuestionThree:
    'Subsequently, a CT scan of the head reveals subependymal nodules. Given the history and findings, which of the following diseases is the most likely diagnosis?',
  webinarLink: 'https://www.youtube.com/live/WFL9GHLCXyA?si=2mMa5AxdtdxYHOyt',
  Detail: 'Detail',
  See_Content: 'See Content',
  whatwillget: 'WHAT YOU WILL GET!',
  Duration: 'Duration',
  goToCart: 'Go to Cart',
  addToCart: 'Add to Cart',
  myCart: 'My Cart',
  makePayment: 'Make Payment',
};
