export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const REQUEST_TOKEN_SUCCESS = 'REQUEST_TOKEN_SUCCESS';
export const REQUEST_TOKEN_FAIL = 'REQUEST_TOKEN_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SESSION = 'SESSION';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAIL = 'SESSION_FAIL';

export const TRENDING_MOVIES = 'TRENDING_MOVIES';
export const TRENDING_MOVIES_SUCCESS = 'TRENDING_MOVIES_SUCCESS';
export const TRENDING_MOVIES_FAIL = 'TRENDING_MOVIES_FAIL';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const RATE_MOVIE = 'RATE_MOVIE';
export const RATE_MOVIE_SUCCESS = 'RATE_MOVIE_SUCCESS';
export const RATE_MOVIE_FAIL = 'RATE_MOVIE_FAIL';

export const DELETE_RATE_MOVIE = 'DELETE_RATE_MOVIE';
export const DELETE_RATE_MOVIE_SUCCESS = 'DELETE_RATE_MOVIE_SUCCESS';
export const DELETE_RATE_MOVIE_FAIL = 'DELETE_RATE_MOVIE_FAIL';

export const GET_RATED_MOVIES = 'GET_RATED_MOVIES';
export const GET_RATED_MOVIES_SUCCESS = 'GET_RATED_MOVIES_SUCCESS';
export const GET_RATED_MOVIES_FAIL = 'GET_RATED_MOVIES_FAIL';

export const ADD_WATCHLIST = 'ADD_WATCHLIST';
export const ADD_WATCHLIST_SUCCESS = 'ADD_WATCHLIST_SUCCESS';
export const ADD_WATCHLIST_FAIL = 'ADD_WATCHLIST_FAIL';

export const GET_WATCHLIST = 'GET_WATCHLIST';
export const GET_WATCHLIST_SUCCESS = 'GET_WATCHLIST_SUCCESS';
export const GET_WATCHLIST_FAIL = 'GET_WATCHLIST_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const TRENDING_PEOPLE = 'TRENDING_PEOPLE';
export const TRENDING_PEOPLE_SUCCESS = 'TRENDING_PEOPLE_SUCCESS';
export const TRENDING_PEOPLE_FAIL = 'TRENDING_PEOPLE_FAIL';
